name: Test

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "docs/**", "dev_scripts/**"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "docs/**", "dev_scripts/**"]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [test]
        default: test
        description: Trigger test manually.
  workflow_call: # make this workflow reusable by release.yml

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # MAVRL's docker container build on uv with LAMMPS with ML-GNNP and ML-SNAP.
      # Required for testing the LAMMPS related methods.
      image: docker.io/materialsvirtuallab/lammps_gnnp
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          uv pip install dgl -f https://data.dgl.ai/wheels/torch-2.4/repo.html
          uv sync
          uv pip install -e .
          apt-get install curl  # Curl is not part of the minimal container image, but is required for CodeCov upload.
      - name: pytest
        run: uv run --group test-models pytest --cov=matcalc --cov-report=xml tests --color=yes
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
